import { StyleSheet } from "react-native";

export default StyleSheet.create({
  scroll: { flexGrow: 1, backgroundColor: "#fff" },
  container: { flexGrow: 1, backgroundColor: "#fff", padding: 24 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginTop: 16,
    marginBottom: 8,
  },
  field: { marginBottom: 12 },
  label: { fontSize: 13, color: "#555", marginBottom: 6 },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    backgroundColor: "#fafafa",
  },
  inputError: { borderColor: "#ff5a5a" },
  errorText: { marginTop: 6, color: "#ff3b30", fontSize: 12 },
  toggleRow: {
    marginTop: 8,
    paddingVertical: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  toggleText: { fontSize: 13, color: "#666" },
  card: {
    borderWidth: 1,
    borderColor: "#eee",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginTop: 6,
    overflow: "visible",
  },
  buttonRow: { flexDirection: "row", gap: 10, marginTop: 16 },
  primaryBtn: {
    flex: 1,
    backgroundColor: "#111827",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  btnDisabled: { opacity: 0.5 },
  secondaryBtn: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryBtnText: { color: "#111827", fontSize: 15, fontWeight: "600" },
});
