import { Platform, StyleSheet } from "react-native";

export default StyleSheet.create({
  scroll: { flexGrow: 1, backgroundColor: "#fff" },
  container: { flexGrow: 1, backgroundColor: "#fff", padding: 24 },
  sectionTitle: {
    fontSize: 16,
    fontFamily: "Ongeulip",
    marginTop: 16,
    marginBottom: 8,
  },
  field: { marginBottom: 12 },
  label: { fontSize: 13, color: "#555", marginBottom: 6, fontFamily: "Ongeulip"},
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    backgroundColor: "#fafafa",
    fontFamily: "Ongeulip",
  },
  inputError: { borderColor: "#ff5a5a", fontFamily: "Ongeulip" },
  errorText: { marginTop: 6, color: "#ff3b30", fontSize: 12, fontFamily: "Ongeulip"},
  toggleRow: {
    marginTop: 8,
    paddingVertical: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 36,
  },
  toggleLeft: {
    flexShrink: 1,
    minWidth: 0,
    marginRight: 8,
  },
  toggleText: {
    fontSize: 13,
    color: "#666",
    fontFamily: "Ongeulip",
    lineHeight: 18,
    ...Platform.select({ android: { includeFontPadding: false } }),
  },
  card: {
    borderWidth: 1,
    borderColor: "#eee",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginTop: 6,
    overflow: "visible",
  },
  buttonRow: { flexDirection: "row", gap: 10, marginTop: 16 },
  primaryBtn: {
    flex: 1,
    backgroundColor: "#111827",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: { color: "#fff", fontSize: 16, fontFamily: "Ongeulip" },
  btnDisabled: { opacity: 0.5 },
  secondaryBtn: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryBtnText: { color: "#111827", fontSize: 15, fontFamily: "Ongeulip" },
  dangerBtn: { marginTop: 18, alignItems: "center", padding: 10 },
  dangerBtnText: {
    color: "#d11",
    fontSize: 13,
    textDecorationLine: "underline",
  },
  // 모달 스타일 (현재 화면에서는 미사용이지만 유지)
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: "Ongeulip",
    marginBottom: 20,
    textAlign: "center",
  },
  modalButtonRow: {
    flexDirection: "row",
    gap: 15,
  },
  modalButton: {
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
    minWidth: 80,
    alignItems: "center",
  },
  modalCancelButton: {
    backgroundColor: "#bbb",
  },
  modalCancelButtonText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Ongeulip",
  },
  modalConfirmButton: {
    backgroundColor: "#FF9898",
  },
  modalConfirmButtonText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Ongeulip",
  },
});
