import { StyleSheet } from "react-native";
import { FontFamily } from './GlobalStyles';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f7f8fa",
  },
  container: {
    flexGrow: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#f7f8fa",
    paddingHorizontal: 0,
  },
  groupTitleContainer: {
    alignItems: "center",
    marginBottom: 18,
  },
  crown: {
    fontSize: 44,
    marginBottom: 2,
    fontFamily: FontFamily.bold,
    color: "#ff6b6b",
    textShadowColor: "rgba(255, 107, 107, 0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  crownIcon: {
    width: 44,
    height: 44,
    marginBottom: 2,
    marginLeft: 4,
  },
  nameContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  heartPartnersContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  heartIcon: {
    width: 18,
    height: 18,
    marginHorizontal: 4,
  },
  myNameText: {
    fontSize: 20,
    fontFamily: FontFamily.bold,
    color: "#222",
  },
  testNameText: {
    fontSize: 18,
    fontFamily: FontFamily.semiBold,
    color: "#222",
  },
  myCardBox: {
    width: 320,
    backgroundColor: "#ffe3ed",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#ffb6c1",
    padding: 18,
    marginBottom: 18,
    shadowColor: "#ffb6c1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  otherCardBox: {
    width: 320,
    backgroundColor: "#fff", // 흰색으로 변경
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#f0f0f0", // 더 연한 회색 테두리
    padding: 18,
    marginBottom: 14,
    shadowColor: "#aaa",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  blueCardBox: {
    backgroundColor: "#e3f0ff",
    borderColor: "#d1e8ff", // 더 연한 파랑색 테두리
    shadowColor: "#7ecbff",
  },
  otherNameText: {
    fontSize: 16,
    fontFamily: FontFamily.semiBold,
    color: "#444",
  },
  blueNameText: {
    fontSize: 16,
    fontFamily: FontFamily.semiBold,
    color: "#2196f3",
  },
  topCardBox: {
    width: 320,
    backgroundColor: "#FDF2F7",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#ffdeec", // 더 연한 빨간색 테두리
    padding: 18,
    marginBottom: 18,
    shadowColor: "#ff5a5a",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 5,
  },
  topNameText: {
    fontSize: 20,
    fontFamily: FontFamily.bold,
    color: "#ff5a5a",
  },
  divider: {
    width: 320,
    height: 1.5,
    backgroundColor: "#e0e0e0", // 회색으로 변경
    marginVertical: 16,
  },
  // 매칭 대기 상태 스타일
  matchingWaitContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  matchingIconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#ffe3ed",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    shadowColor: "#ffb6c1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  matchingIcon: {
    width: 60,
    height: 60,
    tintColor: "#ff6b6b",
  },
  matchingTitleText: {
    fontSize: 20,
    fontFamily: FontFamily.bold,
    color: "#222",
    textAlign: "center",
    marginBottom: 8,
  },
  matchingSubText: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
    fontFamily: "Ongeulip",
  },
  // Add missing styles
  teamNameText: {
    fontSize: 18,
    fontFamily: FontFamily.semiBold,
    color: "#333",
    textAlign: "center",
    maxWidth: 280,
  },
  progressCard: {
    width: 320,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    padding: 18,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  topTeamCard: {
    backgroundColor: "#FDF2F7",
    borderColor: "#ffdeec",
    shadowColor: "#ff5a5a",
    shadowOpacity: 0.2,
  },
  myCard: {
    backgroundColor: "#ffe3ed",
    borderColor: "#ffb6c1",
    shadowColor: "#ffb6c1",
    shadowOpacity: 0.15,
  },
  cardTitle: {
    fontSize: 16,
    fontFamily: FontFamily.semiBold,
    color: "#333",
    marginBottom: 12,
    textAlign: "center",
  },
  section: {
    width: "100%",
    alignItems: "center",
  },
  message: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  errorTitle: {
    fontSize: 20,
    color: "#ff6b6b",
    marginBottom: 15,
    fontFamily: FontFamily.bold,
    textAlign: "center",
  },
  errorMessage: {
    fontSize: 16,
    color: "#666",
    marginBottom: 20,
    fontFamily: FontFamily.regular,
    textAlign: "center",
    lineHeight: 22,
  },
  errorHint: {
    fontSize: 14,
    color: "#999",
    fontFamily: FontFamily.regular,
    textAlign: "center",
    lineHeight: 20,
  },
});

export default styles;
